// English copy for the dashboard design guide. The build script (scripts/build-guide.mjs)
// reads this file, rules.en.json and the shared data files, and writes the static pages.
// fr.js mirrors this file key for key.

export default {
  lang: 'en',
  locale: 'en_CA',
  root: '/projects/dashboard-design-guide/',

  ui: {
    site: 'Enzo Simier',
    projects: 'Projects',
    guide: 'Dashboard design guide',
    guideShort: 'Guide',
    skip: 'Skip to the text',
    chapters: 'Chapters',
    contents: 'Contents',
    next: 'Next',
    previous: 'Previous',
    startReading: 'Start reading',
    backToStart: 'The end · Back to the start',
    backToStartTitle: 'Contents and the plan',
    chapterN: (n) => `Chapter ${n}`,
    rulesRange: (a, b) => `Rules ${a} to ${b}`,
    minutes: (m) => `about ${m} minutes`,
    ruleOf: (n) => `Rule ${n} of 12`,
    rule: (n) => `Rule ${n}`,
    rules: (list) => (list.length === 1 ? `Rule ${list[0]}` : `Rules ${list.slice(0, -1).join(', ')} and ${list[list.length - 1]}`),
    rulesShort: (list) => (list.length === 1 ? `Rule ${list[0]}` : `Rules ${list.join(', ')}`),
    from: 'From',
    inThisChapter: 'In this chapter',
    drawnFrom: 'Drawn from the work of',
    inOurDashboards: 'In our dashboards',
    openCase: 'Open the case study in chapter 7 →',
    oneLine: 'The rule in one line',
    tryIt: 'Try it',
    beforeMoveOn: 'Before you move on',
    beforeNote: 'Check your own dashboard against the chapter',
    checked: (k, n) => `${k} of ${n} checked`,
    showGrid: 'Show the page grid',
    open: 'Open ↗',
    colophon: 'Enzo Simier · Learn dashboard design with me · Set in Instrument Sans and Source Serif 4 on a grid of twelve 64 px columns',
    langLabel: 'Language',
    otherLang: 'Français',
    progress: 'Reading progress',
    menu: 'Chapters',
    close: 'Close',
    portraitOf: (name) => `Portrait of ${name}`,
    noPhoto: 'No free photograph',
    initialsOf: (name) => `${name}, no free photograph available`,
    shelves: 'Three shelves',
    madeBy: 'Made by',
    madeByNames: 'Aicher, Vignelli, Neurath and Arntz, Tufte, Bostock and Carter, Victor, among others',
    allRules: 'All rules',
    showWorksFor: 'Show works for',
    worksShown: (n) => `${n} works`,
    nSources: (n) => `${n} ${n === 1 ? 'source' : 'sources'}`,
    projectsLabel: 'Projects',
    broughtLabel: 'What they brought',
    learnLabel: 'What to learn from them',
    inThisGuide: 'In this guide',
    nPeople: (n) => `${n} ${n === 1 ? 'person' : 'people'}`,
    sixFields: 'Six fields',
    featuredLabel: 'Ten to know first',
    timelineTitle: 'Two centuries on one axis',
    timelineNote: 'Select a face to read who they were and what they made',
    timelineCaption: '<b>The people, by year.</b> Each face is placed at the year of the work this guide draws on, in the lane of the field it came from. Most of the research is recent, and the forms it studies are much older.',
    featuredTitle: 'Ten to know first',
    featuredNote: 'The people whose work carries the most rules, with their projects and a lesson each',
    noteN: (n) => `Note ${n}`,
    reader: 'Who reads it',
    decision: 'What it helps decide',
    builtWith: 'Built with',
    openIt: 'Open it',
    openDashboard: 'Open the dashboard ↗',
    access: 'Access',
    privateCase: 'A private case study, described without the client’s name',
    stillChange: 'What we would still change',
    atAGlance: 'At a glance',
    dashNote: (n, k) => `${n} dashboards and ${k} notes, each note tied to one of the twelve rules`,
  },

  groups: [["Grid and type programmes", "Grid and type", "Designers who treated a layout or a typeface as a system of compatible parts."], ["Cartography", "Cartography", "Map makers who worked out how tone, strength and order carry hierarchy on a crowded sheet."], ["Control-room engineering", "Control rooms", "Engineers who designed for operators who must notice a deviation at once."], ["Business reporting and statistics", "Reporting and statistics", "The people who set the conventions for charts, comparators, notation, tables and plain wording."], ["Perception and uncertainty research", "Perception and uncertainty", "Researchers who measured what readers see in a display and decide from it."], ["Interactive explanation and forecasting practice", "Interaction and forecasting", "People who put controls beside their effects, and who studied how plans are really made."]],

  research: {
    kicker: 'Wider research',
    eightFields: 'Eight fields',
    fieldN: (i, n) => `Field ${i} of ${n}`,
    changes: 'What it changes on a dashboard',
    readFurther: 'Read further',
    facesLabel: 'Among the researchers',
    facesNames: 'Kay and Hullman, Fildes, Cleveland, Heer, Bertin, Vicente and Tory, among many others',
    introLabel: 'About this chapter',
    howToRead: 'How to read it',
    howToReadText: 'Each field opens with what it found, then how strong the evidence is and where it disagrees. The margin lists what it changes on a planning dashboard, and every chart under it can be changed.',
    f0Title: 'The sources, by year and field',
    f0Caption: 'Each dot is one of the 104 references in this chapter, placed at the year of the work cited, in the row of its field; the years before 1950 are compressed. Most of the measured evidence is recent, with 89 references from 1984 or later, and the forms it tests are much older. Select a field to see how far back it reaches, and a dot to read its reference.',
  },

  system: {
    paletteLabel: 'The palette',
    paletteNote: 'Ground, sheet, field and well; slate for what happened, ink for what was lost, one cobalt for what lies ahead.',
    decisionsTitle: 'Six decisions',
    decisionsNote: 'Each one is a rule from chapters 2 to 5, set as a value',
    decisions: [
      { key: 'grid', label: 'Grid · Rule 1', text: 'The page: twelve columns of 64 px with 32 px gutters. The plan: sheets with an 8 px inset and 8 px gutters, holding four instrument cards, eight week columns and rows split three to two.' },
      { key: 'surfaces', label: 'Surfaces · Rule 5', text: 'Ground, sheet, field and well. Higher is lighter. An inner radius is the outer radius minus the inset: 20 for a sheet, 12 for a field.' },
      { key: 'type', label: 'Type · Rule 9', text: 'One family. Values 48 px at weight 600, text and figures 15 px, labels 14 px, ticks 13 px. Tabular, duplexed figures.' },
      { key: 'figures', label: 'Figures · Rule 12', text: 'A bold value over a grey label at each mark. One decimal for money in thousands. A real minus sign. Plain words: lost sales, weeks of stock, left to buy.' },
      { key: 'colour', label: 'Colour · Rule 6', text: 'Slate for what is sold or in stock. One accent for what is expected, its tint for what is planned or arriving, a dashed outline for what is left to buy. Ink for lost sales. No red.' },
      { key: 'interaction', label: 'Interaction · Rule 11', text: 'Controls sit on the chart they change. Pointing highlights and never filters. Every value is printed, so nothing depends on hover.' },
    ],
    lostSales: 'lost sales',
    leftToBuy: 'left to buy',
    tuneTitle: 'Tokens you can move',
    tuneNote: 'Part of the plan, restyled live',
    tuneCaption: '<b>Part of the plan, restyled live.</b> Change the accent, the depth of the surface tones and the corner radius. The token block below rewrites itself to match.',
    tokensLabel: 'Tokens, as set in the figure above',
    copy: 'Copy tokens',
    sourcesIndex: 'Sources, editions and credits',
    sourcesTitle: 'Sources',
    sourcesNote: (n, g) => `${n} works behind the twelve rules, in ${g} groups`,
    keyChecked: 'Checked against the source',
    keyKnown: 'Cited from prior knowledge, not checked again',
    source: 'source',
    editionsTitle: 'Editions',
    editions: [
      ['1 Oct 2026', 'First edition. Design literature gathered for one retail planning case.'],
      ['1 Oct 2026', 'Second edition. Claims re-checked, eight neighbouring fields added, one system proposed.'],
      ['2 Oct 2026', 'Learn dashboard design with me. The people, twelve rules and a model for each, on one page.'],
      ['3 Oct 2026', 'This edition. Nine chapters, the faces behind the rules, the wider research rewritten with charts from published data, the dashboards we made, and a French translation.'],
    ],
    creditsTitle: 'Photographs',
    creditsNote: 'Portraits are freely licensed photographs, shown in greyscale and cropped square, each credited here with its author and licence.',
    noPhoto: (names) => `No free photograph was found for ${names.length} people, who are shown by their initials: ${names.join(', ')}.`,
  },

  meta: {
    title: 'Learn dashboard design with me · Enzo Simier',
    description:
      'A study guide to dashboard design in nine chapters: the people who worked it out, twelve rules with a model for each, what neighbouring fields know, the dashboards we made, works to open, and the system behind them.',
    chapterTitle: (t) => `${t} · Learn dashboard design with me · Enzo Simier`,
  },

  cover: {
    kicker: 'A study guide in nine chapters · Enzo Simier · October 2026',
    title: 'Learn dashboard design with me',
    lede: [
      'A planning dashboard has to show a chain of arithmetic: what demand asks for, what stock can serve, what is on order, how much budget is left to buy, and what margin results. The craft of drawing such chains is older than the screen.',
      'This guide follows the people who worked it out, in grid design, cartography, control rooms, business reporting, perception research and interactive explanation. It shows who they were and what they made, turns their work into twelve rules with a model to play with for each, reads what neighbouring fields have since found, and opens the dashboards we built with those rules.',
    ],
    insideLabel: 'Inside',
    stats: [
      { n: 'people', title: 'People', text: 'Their faces, their projects, and what to learn from each', ch: 1 },
      { n: '12', title: 'Rules', text: 'Each with its sources and a model you can change', ch: 2 },
      { n: '8', title: 'Neighbouring fields', text: 'What forecasting, accounting and control rooms found', ch: 6 },
      { n: 'dashboards', title: 'Dashboards we made', text: 'Opened up, annotated, and checked against the rules', ch: 7, accent: true },
    ],
    castTitle: 'The people behind the rules',
    castNote: (a, b) => `${a} to ${b}, in the order of the work this guide draws on`,
    castCta: 'Meet them in chapter 1 →',
    castTileKicker: 'Chapter 1',
    castTile: (n) => `Meet all ${n} →`,
    exampleTitle: 'One plan runs through the guide',
    exampleNote: 'Five product lines, four weeks, sample data',
    example:
      'A retailer plans four weeks of sales for five product lines. Demand for boots outruns stock in the week of 12 October, because an order of 240 pairs arrives a week too late. Receiving 80 of those pairs a week early would serve the demand. The plan tells that story in the order a planner works: four instruments, then sales and stock week by week, then the buying budget, then the decisions. Each decision has a switch, and every figure recomputes when one is turned on.',
    aboutTitle: 'About the data',
    about:
      'Every figure is sample data and is computed in the page. There is no fitted forecast behind it, so the plan shows no forecast interval anywhere. Rule 10 explains why.',
    contentsNote: 'The chapters can be read in any order',
    insideCol: 'Inside',
  },

  // Nine chapters. `slug` is the folder under the guide root.
  chapters: [
    {
      n: 1, key: 'people', slug: 'people', title: 'The people', minutes: 20,
      desc: 'Who worked out how to draw a plan, what each of them made, what they brought to the craft, and what to take from them.',
      inside: (n) => `${n} people in six fields, on one time axis`,
      standfirst: 'None of the rules in this guide was invented for dashboards. They come from people who spent careers on one part of the problem: how to divide a page, shade a map, keep an operator oriented, report a business, measure what a reader sees, and make a control answer.',
    },
    {
      n: 2, key: 'frame', slug: 'frame-and-measure', title: 'Frame and measure', minutes: 14, rules: [1, 2, 3],
      desc: 'A grid that divides many ways, an instrument for every number, and a test for when a change is real.',
      standfirst: 'Before a single chart is drawn, a dashboard needs three things: a frame that can hold regions of unequal weight, a form that makes every number answer more than one question, and a way to tell news from noise.',
    },
    {
      n: 3, key: 'marks', slug: 'marks-and-surfaces', title: 'Marks and surfaces', minutes: 16, rules: [4, 5, 6],
      desc: 'Draw the arithmetic as a shape, shade for hierarchy and print the quantity, and give each fill one job.',
      standfirst: 'Once the frame holds, the marks have to carry the arithmetic: a law of the plan drawn as a shape, quiet surfaces that group without claiming amounts, and one job for each fill.',
    },
    {
      n: 4, key: 'reading', slug: 'reading-order', title: 'Reading order', minutes: 18, rules: [7, 8, 9],
      desc: 'One axis shared down the page, tables set to be read, and type chosen for figures.',
      standfirst: 'A plan is read down and across. Its weeks should line up from row to row, its tables should be set to be read rather than scanned, and its figures need type that holds still when a row turns bold.',
    },
    {
      n: 5, key: 'candour', slug: 'candour-and-control', title: 'Candour and control', minutes: 16, rules: [10, 11, 12],
      desc: 'Uncertainty shown only when it is earned, each control placed on its consequence, and plain words for every number.',
      standfirst: 'A dashboard that lets a planner act has to be honest about what it knows, put each control where its effect can be seen, and say in plain words what every number is.',
    },
    {
      n: 6, key: 'research', slug: 'neighbouring-fields', title: 'What neighbouring fields know', minutes: 25,
      desc: 'Forecasting, business notation, retail planning, tables, perception, control rooms, research on dashboards and type, each read for what it found.',
      inside: () => 'Eight fields, with charts drawn from published results',
    },
    {
      n: 7, key: 'dashboards', slug: 'dashboards-we-made', title: 'Dashboards we made', minutes: 15,
      desc: 'Our dashboards opened up: the question each one answers, who reads it, and the rules that carry it.',
      inside: (n, k) => `${n} dashboards, ${k} annotations`,
    },
    {
      n: 8, key: 'works', slug: 'works-to-open', title: 'Works to open', minutes: 10,
      desc: 'Books, papers, interfaces and working tools that are worth studying whole.',
      inside: () => 'On paper, on screen and in working tools',
      standfirst: 'A rule is easier to believe after seeing it at work. These are printed sheets, public screens and working tools worth opening and studying whole, each tagged with the rules it shows.',
    },
    {
      n: 9, key: 'system', slug: 'the-system', title: 'The system', minutes: 8,
      desc: 'The grid, tokens and type the plan is built from, a model to tune them, and every source and credit.',
      inside: () => 'Tokens to copy, sources, photo credits',
      standfirst: 'The plan is built from a small set of tokens and six decisions. They are listed here so the design can be rebuilt or adapted, with a model that moves three of them, every source the guide relies on, and a credit for every photograph.',
    },
  ],

  // What each rule chapter adds around the original rule text.
  ruleExtras: {
    1: {
      faces: ['Karl Gerstner', 'Josef Müller-Brockmann', 'Massimo Vignelli', 'Stephen Few'],
      oneLine: 'Choose a width whose sum with one gutter divides by every column count you need, then make the regions unequal on purpose.',
      tryIt: 'Set the calculator to 1200 px with 24 px gutters. Which column counts stop landing on whole pixels, and why?',
      check: 'Width plus one gutter divides by every column count the layout uses, and the regions are unequal on purpose.',
    },
    2: {
      faces: ['Stephen Few', 'Edward Tufte', 'Bill Hollifield', 'Willard Brinton'],
      oneLine: 'Give each headline number its unit, a scale, one comparator and the gap, and leave out bands nobody can define.',
      tryIt: 'Switch off the comparator in the builder. Which question can the card no longer answer, and what would a reader have to remember instead?',
      check: 'Every headline number shows its unit, a scale, a named comparator and the gap.',
    },
    3: {
      faces: ['Walter Shewhart', 'Donald Wheeler'],
      oneLine: 'Treat a change as news only when it leaves the limits of routine variation, and say which reference you used until you have them.',
      tryIt: 'Drag the latest week up until it crosses the upper limit. How far is that from the average, in moving ranges?',
      check: 'A change is called news only when it leaves the limits of routine variation, or the reference is named.',
      calloutNote: { title: 'Not yet in our dashboards', text: 'None of our dashboards has kept a weekly measure long enough for limits of routine variation. Each one names its comparator instead, as this card does with the base case, and that is the candid choice until the history exists.' },
    },
    4: {
      faces: ['William Playfair', 'Kim Vicente', 'Jens Rasmussen'],
      oneLine: 'When the numbers obey a law, draw the law: put both sides on one scale so the answer is a gap the eye can measure.',
      tryIt: 'Raise the stock on order until the dashed gap closes. What does the plan say once the two bars are the same length?',
      check: 'The plan’s law is drawn as a shape the reader can check by eye, not left as numbers to subtract.',
    },
    5: {
      faces: ['Eduard Imhof', 'Stephen Palmer', 'Josef Albers', 'William Cleveland', 'Arthur Robinson'],
      oneLine: 'Let tone say what belongs together and print the number wherever the amount matters; keep strong colour small.',
      tryIt: 'Raise the accent budget until the one blue mark stops standing out. How many accented marks did it take?',
      check: 'Large areas are quiet, groups are made by tone, and every amount that matters is printed.',
    },
    6: {
      faces: ['Rolf Hichert', 'Jacques Bertin'],
      oneLine: 'Give every fill one meaning and let its strength say how firm the quantity is; never let the accent also mean clickable.',
      tryIt: 'Turn the colour off in the figure. Which of the two charts still tells you what is actual and what is planned?',
      check: 'Each fill has one job, firmness is carried by strength, and the accent never doubles as a button.',
    },
    7: {
      faces: ['Étienne-Jules Marey', 'Jacques Bertin', 'William Cleveland', 'David Woods', 'Otl Aicher', 'Tamara Munzner'],
      oneLine: 'Keep one set of columns for time and put every measure under it, so a reader compares by looking down instead of remembering.',
      tryIt: 'Point at the week of 12 October and follow it down. Which product line runs out first, and which order would have saved it?',
      check: 'Every measure sits under one set of week columns, and pointing at a week lights it up in every view.',
    },
    8: {
      faces: ['Andrew Ehrenberg', 'Wim Crouwel'],
      oneLine: 'Edit a table like text: round to the digits that vary, order rows by size, align figures right, and remove every line the eye does not need.',
      tryIt: 'Switch all five rules off, then turn them on one at a time. Which single rule makes the biggest difference to reading the largest value?',
      check: 'Tables are rounded to the digits that vary, ordered by size, right-aligned and nearly free of lines.',
    },
    9: {
      faces: ['Matthew Carter', 'Adrian Frutiger', 'Emil Ruder', 'Jost Hochuli'],
      oneLine: 'Pick a face whose figures are tabular and keep their width in bold, then measure the minus, the percent sign and the decimal point too.',
      tryIt: 'Switch the specimen to Geist and select a row. Which column moves first, and by how much?',
      check: 'Figures are tabular and duplexed, so a bold row moves no column.',
      calloutNote: { title: 'The plan keeps its columns still', text: 'The plan sets every figure in Instrument Sans with tabular figures, whose digits keep their width in bold, so the instruments and the week columns hold still when a decision is switched on.' },
    },
    10: {
      faces: ['Matthew Kay', 'Jessica Hullman', 'Mary Eleanor Spear', 'Marshall Fisher'],
      oneLine: 'Draw a spread only when a model has measured its error, and then draw it as something a reader can count.',
      tryIt: 'Set the stock to 95 units. Count the dots above it. Now try to read the same chance off the interval.',
      check: 'No band or interval appears unless a model has measured its error, and spreads are drawn to be counted.',
    },
    11: {
      faces: ['Ben Shneiderman', 'Bret Victor', 'Mike Bostock', 'Robert Fildes', 'Jeffrey Heer'],
      oneLine: 'Put the control on a chart of what it changes, keep every change visible and reversible, and make an override give its reason.',
      tryIt: 'Drag the point to 30% off. How many tents must sell to beat full price, and is that more than the 180 in stock?',
      check: 'Every control sits on what it changes, and every change is visible, named and reversible.',
    },
    12: {
      faces: ['Ernest Gowers', 'Robin Kinross'],
      oneLine: 'Use the reader’s words, define the terms they will search for, and say plainly what kind of number each figure is.',
      tryIt: 'Pick open-to-buy in the figure. Could a new planner say what it counts, over what period and in what unit, without asking?',
      check: 'Labels use the reader’s words, terms are defined on the screen, and the page says what its numbers are.',
    },
  },
};
