// Texte français du guide de conception de tableaux de bord. Le script de build (scripts/build-guide.mjs)
// lit ce fichier, rules.fr.json et les fichiers de données partagés, et écrit les pages statiques.
// Ce fichier reprend en.js clé pour clé.

const et = (list) => (list.length > 1 ? `${list.slice(0, -1).join(', ')} et ${list[list.length - 1]}` : list.join(''));

export default {
  lang: 'fr',
  locale: 'fr_FR',
  root: '/projects/dashboard-design-guide/fr/',

  ui: {
    site: 'Enzo Simier',
    projects: 'Projets',
    guide: 'Guide de conception de tableaux de bord',
    guideShort: 'Guide',
    skip: 'Aller au texte',
    chapters: 'Chapitres',
    contents: 'Sommaire',
    next: 'Suivant',
    previous: 'Précédent',
    startReading: 'Commencer la lecture',
    backToStart: 'Fin · Retour au début',
    backToStartTitle: 'Le sommaire et le plan',
    chapterN: (n) => `Chapitre ${n}`,
    rulesRange: (a, b) => `Règles ${a} à ${b}`,
    minutes: (m) => `environ ${m} minutes`,
    ruleOf: (n) => `Règle ${n} sur 12`,
    rule: (n) => `Règle ${n}`,
    rules: (list) => (list.length === 1 ? `Règle ${list[0]}` : `Règles ${et(list)}`),
    rulesShort: (list) => (list.length === 1 ? `Règle ${list[0]}` : `Règles ${list.join(', ')}`),
    from: 'D’après',
    inThisChapter: 'Dans ce chapitre',
    drawnFrom: 'D’après les travaux de',
    inOurDashboards: 'Dans nos tableaux de bord',
    openCase: 'Ouvrir l’étude de cas du chapitre 7 →',
    oneLine: 'La règle en une ligne',
    tryIt: 'Essayez',
    beforeMoveOn: 'Avant de poursuivre',
    beforeNote: 'Confrontez votre propre tableau de bord au chapitre',
    checked: (k, n) => `Cochées : ${k} sur ${n}`,
    showGrid: 'Afficher la grille de la page',
    open: 'Ouvrir ↗',
    colophon: 'Enzo Simier · Apprendre à concevoir des tableaux de bord avec moi · Composé en Instrument Sans et Source Serif 4 sur une grille de douze colonnes de 64 px',
    langLabel: 'Langue',
    otherLang: 'English',
    progress: 'Progression de la lecture',
    menu: 'Chapitres',
    close: 'Fermer',
    portraitOf: (name) => `Portrait de ${name}`,
    noPhoto: 'Pas de photo libre',
    initialsOf: (name) => `${name}, aucune photo libre disponible`,
    shelves: 'Trois rayons',
    madeBy: 'Réalisé par',
    madeByNames: 'Aicher, Vignelli, Neurath et Arntz, Tufte, Bostock et Carter, Victor, entre autres',
    allRules: 'Toutes les règles',
    showWorksFor: 'Afficher les œuvres pour',
    worksShown: (n) => `Œuvres affichées : ${n}`,
    nSources: (n) => `${n} ${n > 1 ? 'sources' : 'source'}`,
    projectsLabel: 'Projets',
    broughtLabel: 'Leur apport',
    learnLabel: 'La leçon à en tirer',
    inThisGuide: 'Dans ce guide',
    nPeople: (n) => `${n} ${n > 1 ? 'personnes' : 'personne'}`,
    sixFields: 'Six domaines',
    featuredLabel: 'Dix à connaître d’abord',
    timelineTitle: 'Deux siècles sur un axe',
    timelineNote: 'Sélectionnez un visage pour savoir qui était cette personne et ce qu’elle a réalisé',
    timelineCaption: '<b>Les personnes, par année.</b> Chaque visage est placé à l’année de l’œuvre dont s’inspire ce guide, dans le couloir du domaine dont elle est issue. L’essentiel de la recherche est récent, et les formes qu’elle étudie sont bien plus anciennes.',
    featuredTitle: 'Dix à connaître d’abord',
    featuredNote: 'Les personnes dont le travail porte le plus de règles, avec leurs projets et une leçon pour chacune',
    noteN: (n) => `Note ${n}`,
    reader: 'Qui le lit',
    decision: 'Ce qu’il aide à décider',
    builtWith: 'Réalisé avec',
    openIt: 'L’ouvrir',
    openDashboard: 'Ouvrir le tableau de bord ↗',
    access: 'Accès',
    privateCase: 'Une étude de cas privée, décrite sans le nom du client',
    stillChange: 'Ce que nous changerions encore',
    atAGlance: 'En un coup d’œil',
    dashNote: (n, k) => `${n} tableaux de bord et ${k} notes, chacune liée à l’une des douze règles`,
  },

  groups: [["Programmes de grille et de typographie", "Grille et typographie", "Des graphistes qui ont traité une mise en page ou un caractère comme un système de parties compatibles."], ["Cartographie", "Cartographie", "Des cartographes qui ont établi comment le ton, l’intensité et l’ordre portent la hiérarchie sur une feuille chargée."], ["Ingénierie des salles de contrôle", "Salles de contrôle", "Des ingénieurs qui ont conçu pour des opérateurs devant remarquer un écart sur-le-champ."], ["Rapports de gestion et statistiques", "Rapports et statistiques", "Les personnes qui ont fixé les conventions des graphiques, des comparateurs, de la notation, des tableaux et de la formulation simple."], ["Recherche sur la perception et l’incertitude", "Perception et incertitude", "Des chercheurs qui ont mesuré ce que les lecteurs voient dans un affichage et ce qu’ils en décident."], ["Explication interactive et pratique de la prévision", "Interaction et prévision", "Ceux qui ont placé les commandes à côté de leurs effets, et ceux qui ont étudié comment les plans se font réellement."]],

  research: {
    kicker: 'Recherche élargie',
    eightFields: 'Huit domaines',
    fieldN: (i, n) => `Domaine ${i} sur ${n}`,
    changes: 'Ce que cela change pour un tableau de bord',
    readFurther: 'Pour aller plus loin',
    facesLabel: 'Parmi les chercheurs',
    facesNames: 'Kay et Hullman, Fildes, Cleveland, Heer, Bertin, Vicente et Tory, parmi bien d’autres',
    introLabel: 'À propos de ce chapitre',
    howToRead: 'Comment le lire',
    howToReadText: 'Chaque domaine s’ouvre sur ce qu’il a découvert, puis sur la solidité des preuves et les points de désaccord. La marge indique ce que cela change pour un tableau de bord de planification, et chaque graphique qui suit peut être modifié.',
    f0Title: 'Les sources, par année et par domaine',
    f0Caption: 'Chaque point est l’une des 104 références de ce chapitre, placée à l’année de l’œuvre citée, dans la ligne de son domaine ; les années antérieures à 1950 sont comprimées. L’essentiel des preuves mesurées est récent, avec 89 références de 1984 ou après, et les formes qu’elles mettent à l’épreuve sont bien plus anciennes. Sélectionnez un domaine pour voir jusqu’où il remonte, et un point pour lire sa référence.',
  },

  system: {
    paletteLabel: 'La palette',
    paletteNote: 'Fond, feuille, champ et cuvette ; l’ardoise pour ce qui s’est produit, l’encre pour ce qui a été perdu, un seul cobalt pour ce qui vient.',
    decisionsTitle: 'Six décisions',
    decisionsNote: 'Chacune est une règle des chapitres 2 à 5, fixée en valeur',
    decisions: [
      { key: 'grid', label: 'Grille · Règle 1', text: 'La page : douze colonnes de 64 px avec des gouttières de 32 px. Le plan : des feuilles avec un retrait de 8 px et des gouttières de 8 px, qui accueillent quatre cartes d’instrument, huit colonnes de semaines et des rangées partagées dans un rapport de trois à deux.' },
      { key: 'surfaces', label: 'Surfaces · Règle 5', text: 'Fond, feuille, champ et cuvette. Plus haut, plus clair. Un rayon intérieur est le rayon extérieur moins le retrait : 20 pour une feuille, 12 pour un champ.' },
      { key: 'type', label: 'Typographie · Règle 9', text: 'Une seule famille. Valeurs en 48 px en graisse 600, texte et chiffres en 15 px, libellés en 14 px, repères en 13 px. Chiffres tabulaires, à chasse constante en gras.' },
      { key: 'figures', label: 'Chiffres · Règle 12', text: 'Une valeur en gras au-dessus d’un libellé gris à chaque marque. Une décimale pour les montants en milliers. Un vrai signe moins. Des mots simples : ventes perdues, semaines de stock, reste à acheter.' },
      { key: 'colour', label: 'Couleur · Règle 6', text: 'L’ardoise pour ce qui est vendu ou en stock. Un seul accent pour ce qui est prévu, sa teinte claire pour ce qui est planifié ou en arrivage, un contour pointillé pour ce qui reste à acheter. L’encre pour les ventes perdues. Pas de rouge.' },
      { key: 'interaction', label: 'Interaction · Règle 11', text: 'Les commandes sont posées sur le graphique qu’elles modifient. Pointer met en évidence et ne filtre jamais. Chaque valeur est imprimée, si bien que rien ne dépend du survol.' },
    ],
    lostSales: 'ventes perdues',
    leftToBuy: 'reste à acheter',
    tuneTitle: 'Des tokens à faire varier',
    tuneNote: 'Une partie du plan, restylée en direct',
    tuneCaption: '<b>Une partie du plan, restylée en direct.</b> Changez l’accent, la profondeur des tons de surface et le rayon des coins. Le bloc de tokens ci-dessous se réécrit en conséquence.',
    tokensLabel: 'Les tokens, tels que réglés dans la figure ci-dessus',
    copy: 'Copier les tokens',
    sourcesIndex: 'Sources, éditions et crédits',
    sourcesTitle: 'Sources',
    sourcesNote: (n, g) => `${n} œuvres derrière les douze règles, en ${g} groupes`,
    keyChecked: 'Vérifié dans la source',
    keyKnown: 'Cité de mémoire, non revérifié',
    source: 'source',
    editionsTitle: 'Éditions',
    editions: [
      ['1er oct. 2026', 'Première édition. Des écrits sur le design réunis pour un cas de planification commerciale.'],
      ['1er oct. 2026', 'Deuxième édition. Affirmations revérifiées, huit domaines voisins ajoutés, un système proposé.'],
      ['2 oct. 2026', 'Apprendre à concevoir des tableaux de bord avec moi. Les personnes, douze règles et un modèle pour chacune, sur une seule page.'],
      ['3 oct. 2026', 'Cette édition. Neuf chapitres, les visages derrière les règles, la recherche élargie réécrite avec des graphiques tirés de données publiées, les tableaux de bord que nous avons faits, et une traduction française.'],
    ],
    creditsTitle: 'Photographies',
    creditsNote: 'Les portraits sont des photographies sous licence libre, présentées en niveaux de gris et recadrées au carré, chacune créditée ici avec son auteur et sa licence.',
    noPhoto: (names) => (names.length > 1
      ? `Aucune photographie libre n’a été trouvée pour ${names.length} personnes, représentées par leurs initiales : ${et(names)}.`
      : `Aucune photographie libre n’a été trouvée pour une personne, représentée par ses initiales : ${et(names)}.`),
  },

  meta: {
    title: 'Apprendre à concevoir des tableaux de bord avec moi · Enzo Simier',
    description:
      'Un guide d’étude de la conception de tableaux de bord en neuf chapitres : les personnes qui l’ont mise au point, douze règles avec un modèle pour chacune, ce que savent les domaines voisins, les tableaux de bord que nous avons faits, des œuvres à ouvrir, et le système qui les sous-tend.',
    chapterTitle: (t) => `${t} · Apprendre à concevoir des tableaux de bord avec moi · Enzo Simier`,
  },

  cover: {
    kicker: 'Un guide d’étude en neuf chapitres · Enzo Simier · octobre 2026',
    title: 'Apprendre à concevoir des tableaux de bord avec moi',
    lede: [
      'Un tableau de bord de planification doit montrer une chaîne de calculs : ce que réclame la demande, ce que le stock peut servir, ce qui est en commande, le budget qui reste pour acheter, et la marge qui en résulte. L’art de dessiner de telles chaînes est plus ancien que l’écran.',
      'Ce guide suit les personnes qui l’ont mis au point, dans la conception de grilles, la cartographie, les salles de contrôle, les rapports de gestion, la recherche sur la perception et l’explication interactive. Il montre qui elles étaient et ce qu’elles ont fait, transforme leur travail en douze règles accompagnées chacune d’un modèle à manipuler, lit ce que les domaines voisins ont découvert depuis, et ouvre les tableaux de bord que nous avons construits avec ces règles.',
    ],
    insideLabel: 'Au sommaire',
    stats: [
      { n: 'people', title: 'Personnes', text: 'Leurs visages, leurs projets, et la leçon à tirer de chacune', ch: 1 },
      { n: '12', title: 'Règles', text: 'Chacune avec ses sources et un modèle que vous pouvez modifier', ch: 2 },
      { n: '8', title: 'Domaines voisins', text: 'Ce qu’ont découvert la prévision, la comptabilité et les salles de contrôle', ch: 6 },
      { n: 'dashboards', title: 'Nos tableaux de bord', text: 'Examinés de près, annotés et confrontés aux règles', ch: 7, accent: true },
    ],
    castTitle: 'Les personnes derrière les règles',
    castNote: (a, b) => `De ${a} à ${b}, dans l’ordre des œuvres dont s’inspire ce guide`,
    castCta: 'Les rencontrer au chapitre 1 →',
    castTileKicker: 'Chapitre 1',
    castTile: (n) => `Rencontrer les ${n} →`,
    exampleTitle: 'Un même plan traverse le guide',
    exampleNote: 'Cinq lignes de produits, quatre semaines, données d’exemple',
    example:
      'Une enseigne planifie quatre semaines de ventes pour cinq lignes de produits. La demande de bottes dépasse le stock la semaine du 12 octobre, parce qu’une commande de 240 paires arrive une semaine trop tard. En recevoir 80 une semaine plus tôt suffirait à servir la demande. Le plan raconte cette histoire dans l’ordre où travaille un planificateur : quatre instruments, puis les ventes et le stock semaine par semaine, puis le budget d’achat, puis les décisions. Chaque décision a son interrupteur, et chaque chiffre est recalculé dès que l’on en active un.',
    aboutTitle: 'À propos des données',
    about:
      'Chaque chiffre est une donnée d’exemple, calculée dans la page. Aucune prévision ajustée ne les sous-tend, si bien que le plan ne montre nulle part d’intervalle de prévision. La règle 10 explique pourquoi.',
    contentsNote: 'Les chapitres peuvent se lire dans n’importe quel ordre',
    insideCol: 'Contenu',
  },

  // Neuf chapitres. `slug` est le dossier sous la racine du guide.
  chapters: [
    {
      n: 1, key: 'people', slug: 'les-personnes', title: 'Les personnes', minutes: 20,
      desc: 'Qui a trouvé comment dessiner un plan, ce que chacun a réalisé, ce qu’il a apporté au métier, et ce qu’il faut en retenir.',
      inside: (n) => `${n} personnes dans six domaines, sur un même axe du temps`,
      standfirst: 'Aucune des règles de ce guide n’a été inventée pour les tableaux de bord. Elles viennent de personnes qui ont consacré leur carrière à une partie du problème : diviser une page, ombrer une carte, garder un opérateur orienté, rendre compte de la marche d’une entreprise, mesurer ce que voit un lecteur, et faire répondre une commande.',
    },
    {
      n: 2, key: 'frame', slug: 'cadre-et-mesure', title: 'Cadre et mesure', minutes: 14, rules: [1, 2, 3],
      desc: 'Une grille qui se divise de bien des façons, un instrument pour chaque nombre, et un test pour savoir quand un changement est réel.',
      standfirst: 'Avant de tracer le moindre graphique, un tableau de bord a besoin de trois choses : un cadre capable d’accueillir des régions de poids inégal, une forme qui fait répondre chaque nombre à plus d’une question, et un moyen de distinguer le fait nouveau du bruit.',
    },
    {
      n: 3, key: 'marks', slug: 'marques-et-surfaces', title: 'Marques et surfaces', minutes: 16, rules: [4, 5, 6],
      desc: 'Dessiner l’arithmétique comme une forme, ombrer pour hiérarchiser et imprimer la quantité, et donner un seul rôle à chaque remplissage.',
      standfirst: 'Une fois le cadre en place, les marques doivent porter l’arithmétique : une loi du plan dessinée comme une forme, des surfaces calmes qui regroupent sans prétendre à des montants, et un seul rôle pour chaque remplissage.',
    },
    {
      n: 4, key: 'reading', slug: 'ordre-de-lecture', title: 'Ordre de lecture', minutes: 18, rules: [7, 8, 9],
      desc: 'Un même axe partagé de haut en bas de la page, des tableaux composés pour être lus, et une typographie choisie pour les chiffres.',
      standfirst: 'Un plan se lit de haut en bas et de gauche à droite. Ses semaines doivent s’aligner d’une rangée à l’autre, ses tableaux doivent être composés pour être lus plutôt que survolés, et ses chiffres ont besoin d’un caractère qui reste immobile quand une ligne passe en gras.',
    },
    {
      n: 5, key: 'candour', slug: 'franchise-et-controle', title: 'Franchise et contrôle', minutes: 16, rules: [10, 11, 12],
      desc: 'L’incertitude montrée seulement lorsqu’elle est méritée, chaque commande placée sur sa conséquence, et des mots simples pour chaque nombre.',
      standfirst: 'Un tableau de bord qui permet à un planificateur d’agir doit être honnête sur ce qu’il sait, placer chaque commande là où son effet se voit, et dire en mots simples ce qu’est chaque nombre.',
    },
    {
      n: 6, key: 'research', slug: 'champs-voisins', title: 'Ce que savent les domaines voisins', minutes: 25,
      desc: 'La prévision, la notation de gestion, la planification commerciale, les tableaux, la perception, les salles de contrôle, la recherche sur les tableaux de bord et la typographie, chacun lu pour ce qu’il a découvert.',
      inside: () => 'Huit domaines, avec des graphiques tirés de résultats publiés',
    },
    {
      n: 7, key: 'dashboards', slug: 'nos-tableaux-de-bord', title: 'Nos tableaux de bord', minutes: 15,
      desc: 'Nos tableaux de bord examinés de près : la question à laquelle chacun répond, qui le lit, et les règles qui le portent.',
      inside: (n, k) => `${n} tableaux de bord, ${k} annotations`,
    },
    {
      n: 8, key: 'works', slug: 'oeuvres-a-ouvrir', title: 'Œuvres à ouvrir', minutes: 10,
      desc: 'Des livres, des articles, des interfaces et des outils de travail qui méritent d’être étudiés en entier.',
      inside: () => 'Sur papier, à l’écran et dans les outils de travail',
      standfirst: 'Une règle est plus facile à croire une fois vue à l’œuvre. Voici des feuilles imprimées, des écrans publics et des outils de travail qui méritent d’être ouverts et étudiés en entier, chacun marqué des règles qu’il illustre.',
    },
    {
      n: 9, key: 'system', slug: 'le-systeme', title: 'Le système', minutes: 8,
      desc: 'La grille, les tokens et la typographie dont le plan est fait, un modèle pour les régler, et chaque source et chaque crédit.',
      inside: () => 'Des tokens à copier, les sources, les crédits photo',
      standfirst: 'Le plan est construit à partir d’un petit ensemble de tokens et de six décisions. Ils sont listés ici pour que le design puisse être reconstruit ou adapté, avec un modèle qui en fait varier trois, chaque source sur laquelle s’appuie le guide, et un crédit pour chaque photographie.',
    },
  ],

  // Ce que chaque chapitre de règles ajoute autour du texte de la règle.
  ruleExtras: {
    1: {
      faces: ['Karl Gerstner', 'Josef Müller-Brockmann', 'Massimo Vignelli', 'Stephen Few'],
      oneLine: 'Choisissez une largeur dont la somme avec une gouttière se divise par chaque nombre de colonnes dont vous avez besoin, puis rendez les régions inégales à dessein.',
      tryIt: 'Réglez le calculateur sur 1 200 px avec des gouttières de 24 px. Quels nombres de colonnes cessent de tomber sur des pixels entiers, et pourquoi ?',
      check: 'La largeur plus une gouttière se divise par chaque nombre de colonnes qu’emploie la mise en page, et les régions sont inégales à dessein.',
    },
    2: {
      faces: ['Stephen Few', 'Edward Tufte', 'Bill Hollifield', 'Willard Brinton'],
      oneLine: 'Donnez à chaque chiffre clé son unité, une échelle, un comparateur et l’écart, et laissez de côté les bandes que personne ne sait définir.',
      tryIt: 'Désactivez le comparateur dans la figure. À quelle question la carte ne peut-elle plus répondre, et que faudrait-il qu’un lecteur retienne à la place ?',
      check: 'Chaque chiffre clé affiche son unité, une échelle, un comparateur nommé et l’écart.',
    },
    3: {
      faces: ['Walter Shewhart', 'Donald Wheeler'],
      oneLine: 'Ne tenez un changement pour un fait nouveau que lorsqu’il sort des limites de la variation ordinaire, et dites quelle référence vous employez tant que vous ne les avez pas.',
      tryIt: 'Faites monter la dernière semaine jusqu’à ce qu’elle franchisse la limite haute. À quelle distance de la moyenne se trouve-t-elle, en étendues mobiles ?',
      check: 'Un changement n’est présenté comme un fait nouveau que lorsqu’il sort des limites de la variation ordinaire, ou bien la référence est nommée.',
      calloutNote: { title: 'Pas encore dans nos tableaux de bord', text: 'Aucun de nos tableaux de bord n’a suivi une mesure hebdomadaire assez longtemps pour établir des limites de variation ordinaire. Chacun nomme plutôt son comparateur, comme le fait cette carte avec le scénario central, et c’est le choix honnête tant que l’historique n’existe pas.' },
    },
    4: {
      faces: ['William Playfair', 'Kim Vicente', 'Jens Rasmussen'],
      oneLine: 'Quand les nombres obéissent à une loi, dessinez la loi : placez les deux membres sur une même échelle, pour que la réponse soit un écart que l’œil peut mesurer.',
      tryIt: 'Augmentez le stock en commande jusqu’à ce que l’écart en pointillé se referme. Que dit le plan une fois que les deux barres ont la même longueur ?',
      check: 'La loi du plan est dessinée comme une forme que le lecteur peut vérifier à l’œil, au lieu d’être laissée en nombres à soustraire.',
    },
    5: {
      faces: ['Eduard Imhof', 'Stephen Palmer', 'Josef Albers', 'William Cleveland', 'Arthur Robinson'],
      oneLine: 'Laissez le ton dire ce qui va ensemble et imprimez le nombre partout où le montant compte ; réservez la couleur forte aux petites surfaces.',
      tryIt: 'Augmentez le budget d’accent jusqu’à ce que l’unique marque bleue cesse de ressortir. Combien de marques accentuées a-t-il fallu ?',
      check: 'Les grandes surfaces sont calmes, les groupes sont faits par le ton, et chaque montant qui compte est imprimé.',
    },
    6: {
      faces: ['Rolf Hichert', 'Jacques Bertin'],
      oneLine: 'Donnez à chaque remplissage un seul sens et laissez son intensité dire à quel point la quantité est ferme ; ne laissez jamais l’accent signifier aussi « cliquable ».',
      tryIt: 'Retirez la couleur dans la figure. Lequel des deux graphiques vous dit encore ce qui est réalisé et ce qui est planifié ?',
      check: 'Chaque remplissage a un seul rôle, la fermeté est portée par l’intensité, et l’accent ne sert jamais de bouton.',
    },
    7: {
      faces: ['Étienne-Jules Marey', 'Jacques Bertin', 'William Cleveland', 'David Woods', 'Otl Aicher', 'Tamara Munzner'],
      oneLine: 'Gardez un seul jeu de colonnes pour le temps et placez chaque mesure dessous, pour qu’un lecteur compare en regardant vers le bas au lieu de se souvenir.',
      tryIt: 'Pointez la semaine du 12 octobre et suivez-la vers le bas. Quelle ligne de produits s’épuise la première, et quelle commande l’aurait sauvée ?',
      check: 'Chaque mesure se trouve sous un même jeu de colonnes de semaines, et pointer une semaine l’éclaire dans chaque vue.',
    },
    8: {
      faces: ['Andrew Ehrenberg', 'Wim Crouwel'],
      oneLine: 'Révisez un tableau comme un texte : arrondissez aux chiffres qui varient, classez les lignes par grandeur, alignez les nombres à droite, et retirez chaque filet dont l’œil n’a pas besoin.',
      tryIt: 'Désactivez les cinq règles, puis réactivez-les une à une. Quelle règle, à elle seule, change le plus la lecture de la plus grande valeur ?',
      check: 'Les tableaux sont arrondis aux chiffres qui varient, classés par grandeur, alignés à droite et presque sans filets.',
    },
    9: {
      faces: ['Matthew Carter', 'Adrian Frutiger', 'Emil Ruder', 'Jost Hochuli'],
      oneLine: 'Choisissez un caractère dont les chiffres sont tabulaires et gardent leur chasse en gras, puis mesurez aussi le signe moins, le signe pour cent et le séparateur décimal.',
      tryIt: 'Passez le spécimen en Geist et sélectionnez une ligne. Quelle colonne bouge la première, et de combien ?',
      check: 'Les chiffres sont tabulaires et à chasse constante en gras, si bien qu’une ligne en gras ne déplace aucune colonne.',
      calloutNote: { title: 'Le plan garde ses colonnes immobiles', text: 'Le plan compose chaque chiffre en Instrument Sans, avec des chiffres tabulaires qui gardent leur chasse en gras, si bien que les instruments et les colonnes de semaines restent immobiles quand une décision est activée.' },
    },
    10: {
      faces: ['Matthew Kay', 'Jessica Hullman', 'Mary Eleanor Spear', 'Marshall Fisher'],
      oneLine: 'Ne dessinez une dispersion que lorsqu’un modèle a mesuré son erreur, et dessinez-la alors comme quelque chose qu’un lecteur peut compter.',
      tryIt: 'Réglez le stock sur 95 unités. Comptez les points au-dessus. Essayez maintenant de lire la même probabilité sur l’intervalle.',
      check: 'Aucune bande ni aucun intervalle n’apparaît sans qu’un modèle ait mesuré son erreur, et les dispersions sont dessinées pour être comptées.',
    },
    11: {
      faces: ['Ben Shneiderman', 'Bret Victor', 'Mike Bostock', 'Robert Fildes', 'Jeffrey Heer'],
      oneLine: 'Placez la commande sur un graphique de ce qu’elle modifie, gardez chaque changement visible et réversible, et exigez qu’un ajustement manuel donne sa raison.',
      tryIt: 'Faites glisser le point jusqu’à −30 %. Combien de tentes faut-il vendre pour battre le plein tarif, et est-ce plus que les 180 en stock ?',
      check: 'Chaque commande est placée sur ce qu’elle modifie, et chaque changement est visible, nommé et réversible.',
    },
    12: {
      faces: ['Ernest Gowers', 'Robin Kinross'],
      oneLine: 'Employez les mots du lecteur, définissez les termes qu’il cherchera, et dites clairement de quel type de nombre relève chaque chiffre.',
      tryIt: 'Choisissez le budget d’achat restant dans la figure. Un nouveau planificateur pourrait-il dire ce qu’il compte, sur quelle période et dans quelle unité, sans avoir à demander ?',
      check: 'Les libellés emploient les mots du lecteur, les termes sont définis à l’écran, et la page dit ce que sont ses nombres.',
    },
  },
};
